export const CONFIG_ACTIONS = {
	BASE_CONFIG: 'BASE_CONFIG',
	RESET_QUESTION_LIST: 'RESET_QUESTION_LIST',
	INIT_QUESTION_LIST: 'INIT_QUESTION_LIST',
	ADD_NEW_QUESTION: 'ADD_NEW_QUESTION',
	TOGGLE_QUESTION_MODE: 'TOGGLE_QUESTION_MODE',
	REMOVE_QUESTION: 'REMOVE_QUESTION',
};
